### ISSUE TITLE
Change activation events

### ISSUE THREAD

**Issue by vchirikov** [jashook/vscode-dotnet-insights#3]
Hi, your extension looks like quite useful, but personally I don't like to load it when I don't need to use it.

https://github.com/jashook/vscode-dotnet-insights/blob/c3660ad876373d40094aa53d2d9258aaaf0763e8/dotnetInsights/package.json#L18-L19

docs: https://code.visualstudio.com/api/references/activation-events#Start-up

At the moment, a workaround: disable the extension globally, enable only on the exact workspace where it's necessary

**Comment by jashook** [comment]
0.4.0+ addresses this
