### ISSUE TITLE
Add support for F# decompilation

### ISSUE THREAD

**Issue by baronfel** [jashook/vscode-dotnet-insights#62]
Leaving this here as a note for myself mostly, but I'd love to see if this could be made usable for F# code as well. Might be as simple as `language:fsharp` in the manifest, but might take more digging.  I tried it on my F# projects and while I could manually start the extension, I couldn't get the gc monitoring commands to appear in my palette.

The live stuff would be a bit of a reach given the use of Roslyn for compilation, but I wonder if the PE-based decompilation could work easily?

**Comment by jashook** [comment]
I think the only thing that would not be straight forward is the live bits. They are pretty basic atm anyways. Let me see if I can get something working early tomorrow.

**Comment by jashook** [comment]
Everything else should be language agnostic.

**Comment by baronfel** [comment]
That'd be lovely! Depending on what it takes to support the live stuff I may be able to contribute some support there, I'm fairly familiar with the F# compiler services and APIs.

**Comment by jashook** [comment]
Please feel free, I added some very basic compilation to make the innerloop for microbenchmarking faster. However, I have been wanting (but missing time) to go back and add more functionality. If you are looking to port to what functionality exists, it **should** be rather straightforward :).

Here is the tool that handles the compilation using roslyn (although it seems you may have found it already). https://github.com/jashook/vscode-dotnet-insights/blob/master/roslynHelper/CompilerHelper.cs#L54

**Comment by jashook** [comment]
https://github.com/jashook/vscode-dotnet-insights/pull/63 has the example features I tested, as expected everything seems to work with the exception of the realtimeIL.

**Comment by jashook** [comment]
Closing as V 1.3.0 (published 31-Aug-21 - 23:49 UTC) has the changes to setup the extension for fsharp language load.

**Comment by jashook** [comment]
@baronfel if there are other bugs please open them in a separate issue. Thank you!

**Comment by baronfel** [comment]
Oh wow, great! I'll take it for a spin then :)
