### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Zetsufong12** [jashook/vscode-dotnet-insights#64]
- Issue Type: `Performance`
- Extension Name: `dotnetInsights`
- Extension Version: `1.3.0`
- OS Version: `Windows_NT x64 6.1.7600`
- VS Code version: `1.62.3`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\ADMIN\AppData\Local\Temp\jashoo.dotnetInsights-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by jashook** [comment]
Hello!

I would love to try to make this issue more actionable. Would you mind explaining the repro instructions for the issue? This extension has several out of process executables which could contribute. What are the commands that were used? Or is this something that happens on extension load.

Thank you!

**Comment by jashook** [comment]
Closing due to a lack of repro. Please reopen with a set of repro steps. Thank you!
